### ISSUE TITLE
What is .zshrc.secure ?

### ISSUE THREAD

**Issue by salcode** [aubreypwd/zsh-plugin-reload#1]
I wasn't able to find any information about `.zshrc.secure` with my online searches. Can you clarify what this file is and why you'd want to add it?

**Comment by aubreypwd** [comment]
So I track my `.zshrc` file using version control, so I (personally) have a `.zshrc.secure` file that I never track in version control or at least separately in a private repository. I want to ensure that get's sourced on reload.

**Comment by aubreypwd** [comment]
But I was just thinking that I could maybe add that to my `.zshrc` file (which this sources) and remove it from here...

**Comment by aubreypwd** [comment]
And, it is here:

https://github.com/aubreypwd/vcsh-zsh/blob/master/.zshrc#L98

So I think I'm actually sourcing it twice. I plan to remove...
